mcc -B sgl Engine_sim air_stand_blowdown air_stand_comp air_stand_diesel_heat_addition...
    air_stand_exp air_stand_lp_heat_addition...
    air_stand_otto_heat_addition air_standard bd_func brackroot cancel_but...
    close_assum comp_func complete_comb cycle_assum cycle_calc cycle_preview...
    default_restore default_save diesel_solver dPdt eng_para ...
    eq_comb eq_composition eq_dieselc eq_exp eq_exp_func eq_lpc eq_ottoc...
    eq_solver exp_func get_parameters heat_trans intercooler knock_sim lhv...
    lp_solver mass otto_solver r_browse_call Reactant_Species real_air...
    real_air_comb real_air_dieselc real_air_lpc real_air_ottoc real_bd...
    real_comp real_complete_comb real_dieselc real_eq_comb real_exp real_lpc...
    real_ottoc real_super_comp rev rspecies_ok run_clear Secroot seladdit...
    selcomb selcomp selexbp selmix selthrottle...
    super_func trapuneven vol2theta

%   Function for compiling Engine_sim, with all required functions.  If
%   more functions are added to the program, they must be added to the
%   list above.  
%
%   KMF     April 27/05 Rev 1
%